### ISSUE TITLE
USB Raw devices

### ISSUE THREAD

**Issue by t-kopp** [hgrecco/pyvisa-py#18]
USB Raw devices don't seem to be supported at the moment. Is this just some bug I don't see or is there something missing? If the latter is the case I'll iron out a couple issues with my locally working solution and submit it as a PR

Edit: I've seen a couple devices out there which simply had 1 Bulk in and one out, which is what I would target to add

**Comment by hgrecco** [comment]
They are not supported right now. It is a bug: lack of time of the developers :-D
It would be great if you can submit a PR. Remeber to register the Session class that you create using the following decorator:
```python
@Session.register(constants.InterfaceType.usb, 'RAW')
```

**Comment by t-kopp** [comment]
yes, currently did it dirty by replacing INSTR support :S will clean that up and come back to you

**Comment by hgrecco** [comment]
Mereged in #19
