### ISSUE TITLE
Raspberry visa connection through USB Port

### ISSUE THREAD

**Issue by JessicaAndrade** [hgrecco/pyvisa-py#25]
Is it even possible?

**Comment by BernardoGO** [comment]
I tried to, but could not do it using Rigol Oscilloscope.

**Comment by JessicaAndrade** [comment]
@BernardoGO 
Was it possible to connect through LAN?

**Comment by BernardoGO** [comment]
Yes

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen if necessary.
