### ISSUE TITLE
USB Device Not Detected

### ISSUE THREAD

**Issue by evbo** [hgrecco/pyvisa-py#28]
import visa
    rm = visa.ResourceManager("@py")
    print rm.list_resources()

returns:

    (u'ASRLCOM1::INSTR',)

But using the ni driver:

    import visa
    rm = visa.ResourceManager()
    print rm.list_resources()

returns:

    (u'USB0::0x0957::0x0509::MY42403191::INSTR', u'ASRL1::INSTR', u'ASRL3::INSTR')

Why doesn't the pyvisa-py driver detect the USB device? It is an E5071B Agilent Network Analyzer.

here is my debug:

Machine Details:
   Platform ID:    Windows-XP-5.1.2600-SP3
   Processor:      x86 Family 6 Model 14 Stepping 8, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\src\venv\Scripts\python.exe
   Version:        2.7.9
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          Dec 10 2014 12:24:55 (#default)
   Unicode:        UCS2

PyVISA Version: 1.6.3

Backends:
   ni:
      Version: 1.6.3 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 5243905
         Spec. Version: 5243136
      #2: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 5243905
         Spec. Version: 5243136
   py:
      Version: 0.1
      ASRL INSTR: Available via PySerial (N/A)
      TCPIP INSTR: Available
      USB INSTR: Available via PyUSB (1.0.0b2). Backend: N/A

**Comment by hgrecco** [comment]
You have not installed a Backend for PyUSB. Checkout the PyUSB documentation. 

Within PyVISA we are trying to provide a better error message for this.
See #23  and https://github.com/walac/pyusb/issues/95
