### ISSUE TITLE
Can't connect to usb instrument

### ISSUE THREAD

**Issue by jonnojohnson** [hgrecco/pyvisa-py#3]
I'm on:
Anaconda 2.1.0 (64 bit), Python 2.7.8 on Ubuntu 14.04
pyvisa 1.6.1.dev0 (updated today)
pyvisa-py 0.1.dev0
pyusb 1.0.0b1

I have a Keysight scope connected over USB.

>>> rm.list_resources()
(u'USB0::10893::36894::Unknown::0::INSTR',)

>>> scope = rm.open_resource('USB0::10893::36894::Unknown::0::INSTR')
....
/home/mj-ubuntu/anaconda/lib/python2.7/site-packages/pyvisa-py/protocols/usbtmc.pyc in __init__(self, vendor, product, serial_number, device_filters, timeout, **kwargs)
    160         except usb.core.USBError as e:
    161             #self.log_error("Could not set configuration")
--> 162             raise Exception('failed to set configuration')
    163 
    164         self.usb_intf = self._find_interface(self.usb_dev, self.INTERFACE)

Exception: failed to set configuration

Any thoughts?

**Comment by hgrecco** [comment]
I think this is solved. Feel free to reopen if necessary.

**Comment by flutnic1** [comment]
hgrecco, I have the same timeout problem working with Keysight b2912a unit. Could you please tell me if you solved this problem ? If yes, how ?

Thanks in advance!

**Comment by swirhun** [comment]
I'm having a similar problem with an Agilent 34411A multimeter. The stack trace looks like this. Last week I was able to get about one '*IDN?' query out of the machine and then all subsequent writes and queries failed until I unplugged/replugged/reconnected. It seems there is some bug deep in USB protocol handler. The same code works for a Keithley 2110 multimeter, so it must be some small difference in how they interact over USB which is tripping up pyvisa-py.


Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/resources/resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/highlevel.py", line 191, in open
    sess = cls(session, resource_name, parsed)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/sessions.py", line 184, in __init__
    self.after_parsing()
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/usb.py", line 176, in after_parsing
    self.parsed.serial_number)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/protocols/usbtmc.py", line 232, in __init__
    super(USBTMC, self).__init__(vendor, product, serial_number, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/protocols/usbtmc.py", line 166, in __init__
    raise Exception('failed to set configuration\n %s' % e)
Exception: failed to set configuration
 [Errno 16] Resource busy

**Comment by nat45928** [comment]
Did this ever get solved? I have a Keysight 34461A that is locking up frequently and needs to be disconnected and reconnected all the time.

**Comment by brandonrwin** [comment]
@nat45928 I had a similar problem with a 33500B. After locking up, the NI tools would report a protocol error for the next few reads and then eventually work, so perhaps it was partially equipment related. Updating the 33500B to the latest firmware fixed it for me.

**Comment by swirhun** [comment]
The problem we had with the Keithley 2230-3 has been resolved by sending a
special (non-conforming) command upon connecting, to put the instrument in
remote mode and clear its remote interface. It is unlike any other
instrument I have used. I have also made small local customizations to
pyvisa-py and pyusb to make them work with all our instruments now, so if
anyone is looking for help I could publish some minor suggestions to
GitHub. If I recall correctly, I bypassed the "language selection" portion
and defaulted automatically to English, since it was causing problems with
one Agilent instrument.

Paul

**Comment by swirhun** [comment]
Hi nat45928,

Sorry, my last response was a bit off topic; I sent it by replying to an email on my phone :0. Have a look at https://github.com/pyvisa/pyvisa-py/issues/96. With some local customizations to pyvisa-py and pyusb, we are able to get reliable 34411A operation. I'm assuming the 34461A is a similar instrument. I can send you the changes I made if you want to diff them against your local copy of pyvisa-py and pyusb.

**Comment by lilichen0** [comment]
I can not find the Keithley instrument 2230G-60-3 using Pyvisa in Linux. When I run rm.list_resources(), there only appear an ASRL, no USB device.  The specific information is as follow:

lili@ubuntu:/$ python3 -c "from pyvisa import util; util.get_debug_info()"
Machine Details:
   Platform ID:    Linux-5.4.0-42-generic-x86_64-with-glibc2.29
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /usr/bin/python3
   Version:        3.8.5
   Compiler:       GCC 9.3.0
   Bits:           64bit
   Build:          Jul 28 2020 12:59:40 (#default)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      #1: /usr/lib/x86_64-linux-gnu/libvisa.so.0.0.0:
         found by: auto
         bitness: 64
         Could not get more info:
            VI_ERROR_NSUP_ATTR (-1073807331): The specified attribute is not defined or supported by the referenced object.
   py:
      Version: 0.5.1
      ASRL INSTR: Available via PySerial (3.5)
      USB INSTR: Available via PyUSB (1.1.0). Backend: libusb1
      USB RAW: Available via PyUSB (1.1.0). Backend: libusb1
      TCPIP INSTR: Available 
      TCPIP SOCKET: Available 
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'

lili@ubuntu:/$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvisa
>>> rm=pyvisa.ResourceManager('@py')
>>> rm.list_resources()
('ASRL/dev/ttyS0::INSTR',)
