### ISSUE TITLE
VI_ATTR_TERMCHAR_EN not enabled automatically

### ISSUE THREAD

**Issue by mluthi** [hgrecco/pyvisa-py#62]
While debugging issue #61 I discovered another bug (or missing feature?:-) When specifying a termination character for a read request (e.g. myDevice.read('\r')), the VI_ATTR_TERMCHAR attribute is correctly set, but the VI_ATTR_TERMCHAR_EN attribute is not forced to 'True', which in my case leads to the deadlock described in issue #61. In my opinion passing a termination character as parameter to the read function should automatically enable VI_ATTR_TERMCHAR_EN.

Best Regards,
Matthias

**Comment by hgrecco** [comment]
VI_ATTR_TERMCHAR and VI_ATTR_TERMCHAR_EN are two distinct attributes which in the VISA library are controlled independently (at least in the versions that I am aware of). We do the same in PyVISA-py (as we are building a Python version of the VISA library).

Notice that if you use the higher level classes provided by PyVISA, this is done for you when you set the `read_termination` (see https://github.com/hgrecco/pyvisa/blob/master/pyvisa/resources/messagebased.py#L145)
